name: checks

on: [pull_request]

jobs:
  coding-style:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v4.4.1
