name: clang-tidy

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint with clang-tidy.
        uses: ZedThree/clang-tidy-review@v0.8.2
        with:
          apt_packages: [libgtest-dev, g++-10]
          build_dir: out
          cmake_command: cmake -B out
          config_file: .clang-tidy
