name: clang-tidy

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GoogleTest.
        run: sudo apt install -y libgtest-dev

      - name: Generate build files and compilation database.
        run: cmake -B out

      - name: Lint with clang-tidy.
        uses: ZedThree/clang-tidy-review@v0.7.1
        id: review
        with:
          build_dir: out

      # If there are any comments, fail the check.
      - if: steps.review.total_comments > 0
        run: exit 1
