name: clang-tidy

on: [pull_request]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate build files and compilation database.
        run: cmake -B out

      - name: Lint with clang-tidy.
        uses: ZedThree/clang-tidy-review@v0.7.1
        with:
          build_dir: out
